apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webbion-web-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: argo.tail732e1e.ts.net
      http:
        paths:
          # Route ALL API traffic through Gateway
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gateway-service
                port:
                  number: 3000
          
          # Web app handles everything else
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: webbion-web-app-service
                port:
                  number: 80