apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webbion-web-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: argo.tail732e1e.ts.net
      http:
        paths:
          # user service api
          - path: /api/users(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service-service
                port:
                  number: 3001
          
          # org service api
          - path: /api/orgs(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: org-service-service
                port:
                  number: 3002
          
          # site service api
          - path: /api/sites(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: site-service-service
                port:
                  number: 3003
          
          # booking service api
          - path: /api/bookings(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: booking-service-service
                port:
                  number: 3004
          
          # web app
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: webbion-web-app-service
                port:
                  number: 80