apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: default
  labels:
    app: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway-deployment
  template:
    metadata:
      labels:
        app: gateway-deployment
    spec:
      containers:
        - name: gateway-deployment
          image: ghcr.io/gregmortenoliver/gateway:test
          ports:
            - containerPort: 3000
          env:
            - name: USER_SERVICE_URL
              value: "http://user-service-service:3001"
            - name: ORG_SERVICE_URL
              value: "http://org-service-service:3002"
            - name: SITE_SERVICE_URL
              value: "http://site-service-service:3003"
            - name: BOOKING_SERVICE_URL
              value: "http://booking-service-service:3004"
      imagePullSecrets:
        - name: boliver
