apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-service-deployment
  namespace: default
  labels:
    app: site-service-deployment
spec:
  selector:
    matchLabels:
      app: site-service-deployment
  template:
    metadata:
      labels:
        app: site-service-deployment
    spec:
      containers:
        - name: site-service-deployment
          image: ghcr.io/gregmortenoliver/sites-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: site-mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: site-mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_URL
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@site-mongo-clusterip-service:27017/admin?authSource=admin"
      imagePullSecrets:
        - name: boliver
