apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service-deployment
  namespace: default
  labels:
    app: booking-service-deployment
spec:
  selector:
    matchLabels:
      app: booking-service-deployment
  template:
    metadata:
      labels:
        app: booking-service-deployment
    spec:
      containers:
        - name: booking-service-deployment
          image: ghcr.io/gregmortenoliver/booking-service:latest
          ports:
            - containerPort: 3004
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: booking-mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booking-mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_URL
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@booking-mongo-clusterip-service:27017/admin?authSource=admin"
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0-domain
                  key: PUBLIC_AUTH0_DOMAIN
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: auth0-audience
                  key: PUBLIC_AUTH0_AUDIENCE
      imagePullSecrets:
        - name: boliver
