apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: default
  labels:
    app: user-service-deployment
spec:
  selector:
    matchLabels:
      app: user-service-deployment
  template:
    metadata:
      labels:
        app: user-service-deployment
    spec:
      containers:
        - name: user-service-deployment
          image: ghcr.io/gregmortenoliver/users-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: user-mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_URL
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@user-mongo-clusterip-service:27017/admin?authSource=admin"
      imagePullSecrets:
        - name: boliver
